[package]
name = "MChan"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.0"
axum = "0.8.9"
chacha20poly1305 = "0.10"
getrandom = "0.3"
pulldown-cmark = "0.13"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
hmac = "0.12"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.0", features = ["fs"] }
sqlx = {
version = "0.8",
default-features = false,
features = [
"runtime-tokio",
"sqlite",
"migrate",
"macros",
]
}
serde = { version = "1", features = ["derive"]}
sha2 = "0.10"
uuid = { version = "1.24.0", features = ["v4"] }
